services:
  - type: web
    name: outvin-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OUTVIN_EMAIL
        sync: false
      - key: OUTVIN_PASSWORD
        sync: false
